-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.api_keys
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    hashed_key text COLLATE pg_catalog."default" NOT NULL,
    scope text[] COLLATE pg_catalog."default" DEFAULT '{}'::text[],
    last_used_at timestamp with time zone,
    is_revoked boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone,
    CONSTRAINT api_keys_pkey PRIMARY KEY (id),
    CONSTRAINT api_keys_hashed_key_key UNIQUE (hashed_key)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid,
    user_id uuid,
    api_key_id uuid,
    action text COLLATE pg_catalog."default" NOT NULL,
    entity_type text COLLATE pg_catalog."default",
    entity_id uuid,
    ip_address inet,
    details jsonb,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.classification_cache
(
    error_signature text COLLATE pg_catalog."default" NOT NULL,
    result jsonb NOT NULL,
    confidence double precision,
    used_count integer DEFAULT 1,
    updated_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT classification_cache_pkey PRIMARY KEY (error_signature)
);

CREATE TABLE IF NOT EXISTS public.criticality_levels
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    level integer NOT NULL,
    CONSTRAINT criticality_levels_pkey PRIMARY KEY (id),
    CONSTRAINT criticality_levels_level_key UNIQUE (level),
    CONSTRAINT criticality_levels_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.error_groups
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL,
    group_hash text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    platform_id uuid NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now(),
    last_seen_at timestamp with time zone DEFAULT now(),
    occurrence_count integer DEFAULT 1,
    affected_users_count integer DEFAULT 1,
    severity_id uuid,
    criticality_id uuid,
    recommendation text COLLATE pg_catalog."default",
    is_resolved boolean DEFAULT false,
    resolved_at timestamp with time zone,
    alert_last_sent_at timestamp with time zone,
    alert_last_severity text COLLATE pg_catalog."default",
    CONSTRAINT error_groups_pkey PRIMARY KEY (id),
    CONSTRAINT error_groups_project_id_group_hash_key UNIQUE (project_id, group_hash)
);

CREATE TABLE IF NOT EXISTS public.event_contexts
(
    event_id uuid NOT NULL,
    platform_id uuid NOT NULL,
    language text COLLATE pg_catalog."default",
    os_family text COLLATE pg_catalog."default",
    browser_family text COLLATE pg_catalog."default",
    browser_version text COLLATE pg_catalog."default",
    CONSTRAINT event_contexts_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.event_errors
(
    event_id uuid NOT NULL,
    error_message text COLLATE pg_catalog."default",
    error_stack text COLLATE pg_catalog."default",
    error_line integer,
    error_column integer,
    error_file text COLLATE pg_catalog."default",
    CONSTRAINT event_errors_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.event_performance
(
    event_id uuid NOT NULL,
    load_time_ms integer,
    ttfb_ms integer,
    fcp_ms integer,
    CONSTRAINT event_performance_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.event_urls
(
    event_id uuid NOT NULL,
    page_url text COLLATE pg_catalog."default",
    page_path text COLLATE pg_catalog."default",
    domain text COLLATE pg_catalog."default",
    CONSTRAINT event_urls_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.events
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL,
    api_key_id uuid,
    user_id uuid,
    error_group_id uuid,
    action text COLLATE pg_catalog."default" NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_classified boolean DEFAULT false,
    is_notified boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    event_id uuid NOT NULL,
    error_group_id uuid,
    channel text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    recipient text COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    sent_at timestamp with time zone,
    delivered_at timestamp with time zone,
    error_message text COLLATE pg_catalog."default",
    external_id text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.platforms
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT platforms_pkey PRIMARY KEY (id),
    CONSTRAINT platforms_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    telegram_chat_id character varying(64),
    tech_stack jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_active boolean DEFAULT true,
    CONSTRAINT projects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.severity_levels
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    level integer NOT NULL,
    CONSTRAINT severity_levels_pkey PRIMARY KEY (id),
    CONSTRAINT severity_levels_level_key UNIQUE (level),
    CONSTRAINT severity_levels_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL,
    external_id text COLLATE pg_catalog."default" NOT NULL,
    email_hash text COLLATE pg_catalog."default",
    ip_address inet,
    first_seen_at timestamp with time zone DEFAULT now(),
    last_seen_at timestamp with time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_project_id_external_id_key UNIQUE (project_id, external_id)
);

ALTER TABLE IF EXISTS public.api_keys
    ADD CONSTRAINT api_keys_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_api_key_id_fkey FOREIGN KEY (api_key_id)
    REFERENCES public.api_keys (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.error_groups
    ADD CONSTRAINT error_groups_criticality_id_fkey FOREIGN KEY (criticality_id)
    REFERENCES public.criticality_levels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.error_groups
    ADD CONSTRAINT error_groups_platform_id_fkey FOREIGN KEY (platform_id)
    REFERENCES public.platforms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.error_groups
    ADD CONSTRAINT error_groups_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.error_groups
    ADD CONSTRAINT error_groups_severity_id_fkey FOREIGN KEY (severity_id)
    REFERENCES public.severity_levels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_error_groups_severity
    ON public.error_groups(severity_id);


ALTER TABLE IF EXISTS public.event_contexts
    ADD CONSTRAINT event_contexts_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS event_contexts_pkey
    ON public.event_contexts(event_id);


ALTER TABLE IF EXISTS public.event_contexts
    ADD CONSTRAINT event_contexts_platform_id_fkey FOREIGN KEY (platform_id)
    REFERENCES public.platforms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_event_contexts_platform
    ON public.event_contexts(platform_id);


ALTER TABLE IF EXISTS public.event_errors
    ADD CONSTRAINT event_errors_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS event_errors_pkey
    ON public.event_errors(event_id);


ALTER TABLE IF EXISTS public.event_performance
    ADD CONSTRAINT event_performance_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS event_performance_pkey
    ON public.event_performance(event_id);


ALTER TABLE IF EXISTS public.event_urls
    ADD CONSTRAINT event_urls_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS event_urls_pkey
    ON public.event_urls(event_id);


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_api_key_id_fkey FOREIGN KEY (api_key_id)
    REFERENCES public.api_keys (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_error_group_id_fkey FOREIGN KEY (error_group_id)
    REFERENCES public.error_groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_events_error_group
    ON public.events(error_group_id);


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_events_user_id
    ON public.events(user_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_error_group_id_fkey FOREIGN KEY (error_group_id)
    REFERENCES public.error_groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notifications_event_id
    ON public.notifications(event_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_users_project_id
    ON public.users(project_id);

END;