"""init 4NF schema

Revision ID: 90f3809e5720
Revises: 
Create Date: 2026-02-24 14:16:50.674228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f3809e5720'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_performance')
    op.alter_column('api_keys', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_keys', 'hashed_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_keys', 'scope',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index('idx_api_keys_hashed_key', table_name='api_keys', postgresql_using='hash')
    op.drop_column('api_keys', 'last_used_at')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_project_time', table_name='audit_logs')
    op.alter_column('classification_cache', 'error_signature',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('criticality_levels', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('error_groups', 'group_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('error_groups', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_error_groups_last_seen', table_name='error_groups')
    op.drop_index('idx_error_groups_project_hash', table_name='error_groups')
    op.drop_index('idx_error_groups_severity', table_name='error_groups')
    op.alter_column('event_contexts', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_contexts', 'os_family',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_contexts', 'browser_family',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_contexts', 'browser_version',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_event_contexts_browser', table_name='event_contexts')
    op.drop_index('idx_event_contexts_os', table_name='event_contexts')
    op.drop_index('idx_event_contexts_platform', table_name='event_contexts')
    op.alter_column('event_errors', 'error_file',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_event_errors_message_gin', table_name='event_errors', postgresql_using='gin')
    op.alter_column('event_urls', 'page_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_urls', 'page_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('event_urls', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_event_urls_domain', table_name='event_urls')
    op.drop_index('idx_event_urls_path', table_name='event_urls')
    op.alter_column('events', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_events_error_group', table_name='events', postgresql_where='(error_group_id IS NOT NULL)')
    op.drop_index('idx_events_project_timestamp', table_name='events')
    op.drop_index('idx_events_user_id', table_name='events', postgresql_where='(user_id IS NOT NULL)')
    op.alter_column('notifications', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'recipient',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'external_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_index('idx_notifications_event_id', table_name='notifications')
    op.drop_index('idx_notifications_status', table_name='notifications')
    op.drop_column('notifications', 'delivered_at')
    op.drop_column('notifications', 'error_message')
    op.drop_column('notifications', 'sent_at')
    op.alter_column('platforms', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('severity_levels', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'external_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_users_last_seen', table_name='users')
    op.drop_index('idx_users_project_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_project_id', 'users', ['project_id'], unique=False)
    op.create_index('idx_users_last_seen', 'users', [sa.text('last_seen_at DESC')], unique=False)
    op.alter_column('users', 'email_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'external_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('severity_levels', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('platforms', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('notifications', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('idx_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('idx_notifications_event_id', 'notifications', ['event_id'], unique=False)
    op.create_index('idx_notifications_created_at', 'notifications', [sa.text('created_at DESC')], unique=False)
    op.alter_column('notifications', 'external_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notifications', 'recipient',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notifications', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('idx_events_user_id', 'events', ['user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_events_project_timestamp', 'events', ['project_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_events_error_group', 'events', ['error_group_id'], unique=False, postgresql_where='(error_group_id IS NOT NULL)')
    op.alter_column('events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('events', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('idx_event_urls_path', 'event_urls', ['page_path'], unique=False)
    op.create_index('idx_event_urls_domain', 'event_urls', ['domain'], unique=False)
    op.alter_column('event_urls', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_urls', 'page_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_urls', 'page_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_event_errors_message_gin', 'event_errors', [sa.text("to_tsvector('russian'::regconfig, COALESCE(error_message, ''::text))")], unique=False, postgresql_using='gin')
    op.alter_column('event_errors', 'error_file',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_event_contexts_platform', 'event_contexts', ['platform_id'], unique=False)
    op.create_index('idx_event_contexts_os', 'event_contexts', ['os_family'], unique=False)
    op.create_index('idx_event_contexts_browser', 'event_contexts', ['browser_family'], unique=False)
    op.alter_column('event_contexts', 'browser_version',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_contexts', 'browser_family',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_contexts', 'os_family',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event_contexts', 'language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_error_groups_severity', 'error_groups', ['severity_id'], unique=False)
    op.create_index('idx_error_groups_project_hash', 'error_groups', ['project_id', 'group_hash'], unique=False)
    op.create_index('idx_error_groups_last_seen', 'error_groups', [sa.text('last_seen_at DESC')], unique=False)
    op.alter_column('error_groups', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('error_groups', 'group_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('criticality_levels', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('classification_cache', 'error_signature',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('idx_audit_logs_project_time', 'audit_logs', ['project_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('api_keys', sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('idx_api_keys_hashed_key', 'api_keys', ['hashed_key'], unique=False, postgresql_using='hash')
    op.alter_column('api_keys', 'scope',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('api_keys', 'hashed_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('event_performance',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('load_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ttfb_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fcp_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_performance_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name='event_performance_pkey')
    )
    # ### end Alembic commands ###
